### ISSUE TITLE
Project Readme

### ISSUE THREAD

**Issue by kiptanuiBoaz** [Campo-Yangu/campus-tech-blog#2]
Write a comprehensive description entailing what kind of project it is, how it can be useful, how to install and use it, the list of authors, guidelines for contributing, a license notice, and whatever else the developers would want other people to read.
You may also include other relevant information.
I have included the link to an article on writing a good ReadME check it out (_if it's helpful_) and create a PR once you are done.

[how to write a readme](https://www.makeareadme.com/)

**Comment by IanoNjuguna** [comment]
I'll take this up.

**Comment by kiptanuiBoaz** [comment]
All the best
Create your own fork and work from there, and create a PR when you're done

**Comment by teddylumidi** [comment]
Great start

**Comment by kiptanuiBoaz** [comment]
Hey @IanoNjuguna  any luck with the readme?

**Comment by IanoNjuguna** [comment]
I'll submit a PR by evening

**Comment by kiptanuiBoaz** [comment]
This some good work @IanoNjuguna
